import React, { useState, useMemo, useCallback, useEffect, useRef } from "react";
import {
  LineChart, Line, XAxis, YAxis, CartesianGrid, Tooltip, Legend, ResponsiveContainer, ReferenceLine,
} from "recharts";
import { Search, Download, Award, TrendingUp, TrendingDown, Minus, PawPrint, Save, CheckCircle, Loader } from "lucide-react";
import * as XLSX from "xlsx";

import { createClient } from "@supabase/supabase-js";
const SUPABASE_URL  = "https://kyexopavvsbyrdwtefca.supabase.co";
const SUPABASE_ANON = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imt5ZXhvcGF2dnNieXJkd3RlZmNhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODM5MTEzMDMsImV4cCI6MjA5OTQ4NzMwM30.NFVWMgeYSEOETDe_f8yH6TbULtxWuodFORgy8WImG_8";
const supabase = createClient(SUPABASE_URL, SUPABASE_ANON);

const CT_LABELS = {
  Member: "Socios / Miembros",
  User: "Usuarios (No Socios)",
  Canine_Collaborator: "Colaboradoras Caninas",
};
const CT_COLORS = {
  Member: "#B98A3F",
  User: "#1C2B45",
  Canine_Collaborator: "#5C7A5E",
};
const CT_ORDER = ["Canine_Collaborator","Member", "User"];

function lastNonNull(series, field) {
  for (let i = series.length - 1; i >= 0; i--) {
    if (series[i][field] !== null && series[i][field] !== undefined) {
      return series[i];
    }
  }
  return null;
}

function secondLastNonNull(series, field, beforeYear) {
  for (let i = series.length - 1; i >= 0; i--) {
    if (series[i].year < beforeYear && series[i][field] !== null && series[i][field] !== undefined) {
      return series[i];
    }
  }
  return null;
}

function prevYearEntry(series, beforeYear) {
  for (let i = series.length - 1; i >= 0; i--) {
    if (series[i].year < beforeYear) return series[i];
  }
  return null;
}

function valueForYear(series, field, year) {
  const entry = series.find((p) => p.year === year);
  if (!entry) return null;
  if (entry[field] === null || entry[field] === undefined) return null;
  return entry;
}

function pctChange(a, b) {
  if (a === null || a === undefined || a === 0) return null;
  return (b - a) / a;
}

function fmtEUR(v) {
  if (v === null || v === undefined || Number.isNaN(v)) return (0).toLocaleString("es-ES", { minimumFractionDigits: 2, maximumFractionDigits: 2 }) + " €";
  return v.toLocaleString("es-ES", { minimumFractionDigits: 2, maximumFractionDigits: 2 }) + " €";
}

function fmtPct(v) {
  if (v === null || v === undefined || Number.isNaN(v)) return "—";
  const s = (v * 100).toLocaleString("es-ES", { minimumFractionDigits: 1, maximumFractionDigits: 1 });
  return (v > 0 ? "+" : "") + s + "%";
}

function TrendIcon({ v }) {
  if (v === null || v === undefined) return <Minus size={14} style={{ opacity: 0.35 }} />;
  if (v > 0.0005) return <TrendingUp size={14} color="#5C7A5E" />;
  if (v < -0.0005) return <TrendingDown size={14} color="#A6452E" />;
  return <Minus size={14} style={{ opacity: 0.5 }} />;
}

const RSCE_DATA = {"products": ["1ª CARTILLA", "1ª CARTILLA PERROS DE RASTRO DEL GRUPO 6º", "2ª CARTILLA", "2ª CARTILLA PERROS DE RASTRO DEL GRUPO 6º", "3ª CARTILLA", "3ª CARTILLA PERROS DE RASTRO DEL GRUPO 6º", "3ª MEDICION EJEMPLARES PARA DETERMINAR CATEGORIA DE PARTICIPACIÓN (según reglamento)", "3ª MEDICIÓN EJEMPLARES PARA DETERMINAR CATEGORIA DE PARTICIPACIÓN (según Reglamento)", "3ª MEDICIÓN EJEMPLARES PARA DETERMINAR CATEGORÍA DE PARTICIPACIÓN (según Reglamento)", "4ª CARTILLA Y SUCESIVAS HASTA EL NÚMERO MÁXIMO DE PERROS QUE COMPONEN UNA JAURÍA SEGÚN EL REGLAMENTO", "4ª CARTILLA Y SUCESIVAS HASTA EL NÚMERO MÁXIMO DE PERROS QUE PUEDAN COMPONER UNA JAURÍA (según Reglamento)", "ANALÍTICA IDENTIFICACIÓN GENÉTICA CANINA A.D.N. / PRUEBAS DE PARTERNIDAD (por perro) - SALIVA", "ANALÍTICA IDENTIFICACIÓN GENÉTICA CANINA A.D.N. / PRUEBAS DE PARTERNIDAD (por perro) - SANGRE", "ANALÍTICA IDENTIFICACIÓN GENÉTICA CANINA A.D.N. / PRUEBAS DE PATERNIDAD (por perro) / SALIVA", "ANALÍTICA IDENTIFICACIÓN GENÉTICA CANINA A.D.N. / PRUEBAS DE PATERNIDAD (por perro) / SANGRE", "ANALÍTICA IDENTIFICACIÓN GENÉTICA CANINA ADN / PRUEBAS DE PATERNIDAD (por perro)", "ANALÍTICA IDENTIFICACIÓN GENÉTICA CANINA ADN / PRUEBAS DE PATERNIDAD (por perro) / SALIVA", "ANALÍTICA IDENTIFICACIÓN GENÉTICA CANINA ADN / PRUEBAS DE PATERNIDAD (por perro) / SANGRE", "ANOTACIÓN DE TÍTULOS", "ANOTACIÓN EN BASE DE DATOS DE PRUEBA ADN SIN ACOGERSE AL CONVENIO RSCE – HISPALAB (por perro)", "ANOTACIÓN EN BASE DE DATOS DE PRUEBA GENÉTICA O DE DISPLASIA (por prueba)", "ANOTACIÓN EN BASE DE DATOS PRUEBA ADN", "ANOTACIÓN PRUEBA DE DISPLASIA", "BAJA DE UN PERRO EN EL L.O.E. / R.R.C. (para su posterior inscripción en otros libros genealógicos)", "BAJA DE UN PERRO EN EL L.O.E./R.R.C.", "BAJA DE UN PERRO EN EL L.O.E./R.R.C. (para su posterior inscripción de otros libros genealógicos)", "BAJA DE UN PERRO EN EL LOE/RRC (para su posterior inscripción de otros libros genealógicos)", "CAMBIO PEDIGREE CUATRO GENERACIONES A PEDIGREE ORO SIN TRANSFERENCIA DE PROPIEDAD", "CAMBIO PEDIGREE TRES GENERACIONES A PEDIGREE ORO SIN TRANSFERENCIA DE PROPIEDAD", "CARTILLA ASISTENTE", "CARTILLA DE ASISTENTE", "CARTILLA DE PRUEBAS DEPORTIVAS DE  CAZA", "CARTILLA DE PRUEBAS DEPORTIVAS DE AGILITY", "CARTILLA DE PRUEBAS DEPORTIVAS DE CAZA", "CARTILLA DE PRUEBAS DEPORTIVAS DE TRABAJO", "CARTILLA DE PRUEBAS DEPORTIVAS DE TRABAJO PARA PERROS SIN PEDIGREE", "CARTILLA DE PRUEBAS DEPORTIVAS PARA PERROS SIN PEDIGREE", "CARTILLA PARA PRUEBAS DE CAMPO", "CARTILLA PARA PRUEBAS DEPORTIVAS DE CAMPO", "CARTILLA PARA PRUEBAS DEPORTIVAS POLIVALENTES - PERRO DE AGUA ESPAÑOL", "CERTIFICADO  DE COLA CORTA", "CERTIFICADO DE COLA CORTA", "CERTIFICADO DE TRABAJO", "CERTIFICADO DE TRABAJO PERROS DE MUESTRA RASTRO Y MADRIGUERA", "CERTIFICADO DE TRABAJO PERROS DE MUESTRA, RASTRO Y MADRIGUERA", "CERTIFICADO INTERNACIONAL DE DISPLASIA", "CESIÓN TEMPORAL DE PROPIEDAD DE LA HEMBRA REPRODUCTORA", "CESIÓN TEMPORAL DE PROPIEDAD DE LOS REPRODUCTORES", "CONFIRMACION DE RAZA (PERROS RAZAS ESPAÑOLAS)", "CONFIRMACION DE RAZA (perros de razas españolas)", "CONFIRMACIÓN DE RAZA (PERROS GRUPOS ÉTINICOS)", "CONFIRMACIÓN DE RAZA (perros de razas españolas)", "CUOTA ABONADO", "CUOTA ABONO JOVEN", "CUOTA ANUAL CLUB AGILITY", "CUOTA ANUAL CLUB DE AGILITY", "CUOTA ANUAL GRUPO DE TRABAJO", "CUOTA ANUAL MULTIDISCIPLINAR", "CUOTA ANUAL SOCIO", "CUOTA INICIAL SOCIO (incluida la cuota del primer año natural)", "CUOTA INICIAL SOCIO, incluida la cuota del primer año natural (260 + 30)", "DUPLICADO AFIJO", "DUPLICADO DE AFIJO", "DUPLICADO DE PEDIGREE CUATRO GENERACIONES", "DUPLICADO DE PEDIGREE TRES GENERACIONES", "DUPLICADO EXPORT PEDIGREE CUATRO GENERACIONES", "DUPLICADO EXPORT PEDIGREE TRES GENERACIONES", "DUPLICADO JUSTIFICANTE DE INSCRIPCIÓN", "DUPLICADO PEDIGREE_RSCE", "DUPLICADO PEDIGREE_RSCE DE EXPORTACIÓN 3 GENERACIONES", "DUPLICADO PEDIGREE_RSCE DE EXPORTACIÓN 4 GENERACIONES", "DUPLICADO PEDIGREE_RSCE DE EXPORTACIÓN CUATRO GENERACIONES EN PAPEL", "DUPLICADO PEDIGREE_RSCE DE EXPORTACIÓN TRES GENERACIONES EN PAPEL", "DUPLICADO PEDIGREE_RSCE EN PAPEL", "EDIGREE_RSCE PREMIUM TRES GENERACIONES SIN TRANSFERENCIA", "EXCEPCION, RECARGO 300% (más de 12 meses y menos de 18)  Art, 5.k) Reglamento L.O.E.", "EXCEPCION: RECARGO 300% (más de 12 meses y menos de 18 meses)  Reglamento L.O.E.", "EXPEDICIÓN DE INFORMES (precio por folio impreso)", "EXPEDICIÓN TITULOS DE CAMPEONES", "EXPEDICIÓN TITULOS LATIN CHAMPION", "EXPEDICIÓN TÍTULOS \"LATIN CHAMPION\"", "EXPEDICIÓN TÍTULOS DE CAMPEONES", "EXPEDICIÓN TÍTULOS “LATIN CHAMPION”", "FORMULARIO IDENTIFICACIÓN (por cachorro al notificar nacimiento)", "FORMULARIO IDENTIFICACIÓN (por cachorro al notificar nacimiento) EN ORIGEN", "FORMULARIO IDENTIFICACIÓN (por cachorro al notificar nacimiento) RSCE", "IMPRESO ALTA CAMADA", "IMPRESO ALTA DE CAMADA", "IMPRESO ALTA DE CAMADA (GRUPOS ÉTNICOS)", "IMPRESO ALTA DE CAMADA (PERROS DE RAZA)", "IMPRESO DIPLOMA DE INICIACIÓN (original y 3 copias)", "IMPRESO HOJA DE CALIFICACIÓN – PRUEBAS PERRO DE AGUA ESPAÑOL", "IMPRESO PARA PRUEBAS CACT - CACIT", "IMPRESO PARA PRUEBAS DE C.A.C.T. - C.A.C.I.T.", "IMPRESO PARA PRUEBAS DE CACT – CACIT", "IMPRESO PRUEBAS APTITUDES NATURALES (original y 3 copias)", "INFORMES SOLICITADOS A LA R.S.C.E. (precio por folio impreso)", "INFORMES SOLICITADOS A LA RSCE (precio por folio impreso", "INFORMES SOLICITADOS A LA RSCE (precio por folio impreso)", "INSCRIPCION DE OTROS LIBROS GENEALOGICOS (NO ADMITE PLUS DE URGENCIA)", "INSCRIPCION PERROS DE OTROS LIBROS GENEALÓGICOS (ESTE TRÁMITE NO ADMITE PLUS DE URGENCIA)", "INSCRIPCIÓN CACHORRO", "INSCRIPCIÓN CACHORRO ACCESS LBO/RBR", "INSCRIPCIÓN CACHORRO DE RAZAS ESPAÑOLAS BONIFICADAS", "INSCRIPCIÓN CACHORRO EN EL REGISTRO DE GRUPOS ÉTNICOS", "INSCRIPCIÓN CACHORRO PREMIUM LOE/RRC", "INSCRIPCIÓN CACHORRO RAZAS ESPAÑOLAS BONIFICADAS ( Del 01/05/2023 al 30/04/2024)", "INSCRIPCIÓN CACHORRO RAZAS ESPAÑOLAS BONIFICADAS ( Del 01/05/2024 al 30/04/2025)", "INSCRIPCIÓN IMPORTADOS", "INSCRIPCIÓN PERRO con más de 18 meses aportando prueba ADN progenitores y huella genética de compatibilidad", "INSCRIPCIÓN PERROS DE OTROS LIBROS GENEALÓGICOS", "INSCRIPCIÓN PERROS DE OTROS LIBROS GENEALÓGICOS - ESTE TRÁMITE NO ADMITE PLUS DE URGENCIA", "INSCRIPCIÓN PERROS PROCEDENTES DE OTROS LIBROS GENEALÓGICOS", "INSCRIPCIÓN PERROS PROCEDENTES DE OTROS LIBROS GENEALÓGICOS (ESTE TRÁMITE NO ADMITE PLUS DE URGENCIA)", "LICENCIA INCIAL", "LICENCIA INICIAL", "MEJORA A PEDIGREE_RSCE PLUS CUATRO GENERACIONES SIN TRANSFERENCIA", "MEJORA A PEDIGREE_RSCE PLUS RRC (sin genealogía completa) CON TRANSFERENCIA", "MEJORA A PEDIGREE_RSCE PLUS RRC (sin genealógica completa) SIN TRANSFERENCIA", "MEJORA A PEDIGREE_RSCE PLUS TRES GENERACIONES SIN TRANSFERENCIA", "MEJORA DE PEDIGREE_RSCE ACCESS LBO A PEDIGREE_RSCE PREMIUM LOE CUATRO GENERACIONES SIN TRANSFERENCIA", "MEJORA DE PEDIGREE_RSCE ACCESS LBO A PEDIGREE_RSCE PREMIUM LOE CUATRO GENERACIONES SIN TRANSFERENCIA EN PAPEL", "MEJORA DE PEDIGREE_RSCE ACCESS LBO A PEDIGREE_RSCE PREMIUM LOE TRES GENERACIONES SIN TRANSFERENCIA", "MEJORA DE PEDIGREE_RSCE ACCESS LBO A PEDIGREE_RSCE PREMIUM LOE TRES GENERACIONES SIN TRANSFERENCIA EN PAPEL", "MEJORA DE PEDIGREE_RSCE ACCESS RBR A PEDIGREE_RSCE PREMIUM RRC SIN TRANSFERENCIA", "MEJORA DE PEDIGREE_RSCE ACCESS RBR A PEDIGREE_RSCE PREMIUM RRC SIN TRANSFERENCIA EN PAPEL", "NOTIFICACIÓN NACIMIENTO CACHORRO (formulario de identificación)", "OTRAS ANOTACIONES EN EL LOE / RRC / RGE", "PEDIGREE CON TRANSFERENCIA CUATRO GENERACIONES  (SI CONSTAN EN EL L.O.E.)", "PEDIGREE CON TRANSFERENCIA CUATRO GENERACIONES  (si consta en el L.O.E..)", "PEDIGREE CON TRANSFERENCIA CUATRO GENERACIONES (si la genealogía consta en la base de datos del L.O.E.)", "PEDIGREE CON TRANSFERENCIA CUATRO GENERACIONES (si la genealogía consta en la base de datos del LOE)", "PEDIGREE CON TRANSFERENCIA TRES GENERACIONES", "PEDIGREE DE EXPORTACION (4 generaciones)", "PEDIGREE DE EXPORTACIÓN CUATRO GENERACIONES (si la genealogía consta en la base de datos del L.O.E.)", "PEDIGREE DE EXPORTACIÓN CUATRO GENERACIONES (si la genealogía consta en la base de datos del LOE)", "PEDIGREE DE EXPORTACIÓN TRES GENERACIONES", "PEDIGREE ORO", "PEDIGREE ORO CON TRANSFERENCIA DE PROPIEDAD", "PEDIGREE ORO SIN TRANSFERENCIA", "PEDIGREE PARA PERROS INSCRITOS EN EL R.R.C. (sin genealógica completa)", "PEDIGREE PARA PERROS INSCRITOS EN EL RRC (sin genealógia completa)", "PEDIGREE PARA PERROS INSCRITOS EN EL RRC (sin genealógica completa)", "PEDIGREE SIN TRANSFERENCIA", "PEDIGREE SIN TRANSFERENCIA CUATRO GENERACIONES  (SI CONSTAN EN EL L.O.E.)", "PEDIGREE SIN TRANSFERENCIA CUATRO GENERACIONES  (si consta en el  L.O.E.)", "PEDIGREE SIN TRANSFERENCIA CUATRO GENERACIONES (Si la genealogía consta en la base de datos del LOE)", "PEDIGREE SIN TRANSFERENCIA CUATRO GENERACIONES (si la genealogía consta en la base de datos del L.O.E.)", "PEDIGREE SIN TRANSFERENCIA CUATRO GENERACIONES (si la genealogía consta en la base de datos del LOE)", "PEDIGREE_RSCE ACCESS LBO CON TRANSFERENCIA", "PEDIGREE_RSCE ACCESS LBO SIN TRANSFERENCIA", "PEDIGREE_RSCE ACCESS RBR CON TRANSFERENCIA", "PEDIGREE_RSCE ACCESS RBR CON TRANSFERENCIA EN PAPEL", "PEDIGREE_RSCE ACCESS RBR SIN TRANSFERENCIA", "PEDIGREE_RSCE ACCESS SIN TRANSFERENCIA EN PAPEL", "PEDIGREE_RSCE ACCESS TRES GENERACIONES CON TRANSFERENCIA EN PAPEL", "PEDIGREE_RSCE DE EXPORTACION 3 GENERACIONES", "PEDIGREE_RSCE DE EXPORTACION 4 GENERACIONES", "PEDIGREE_RSCE DE EXPORTACIÓN CUATRO GENERACIONES EN PAPEL", "PEDIGREE_RSCE DE EXPORTACIÓN TRES GENERACIONES EN PAPEL", "PEDIGREE_RSCE PLUS CUATRO GENERACIONES CON TRANSFERENCIA", "PEDIGREE_RSCE PLUS CUATRO GENERACIONES CON TRANSFERENCIA EN PAPEL", "PEDIGREE_RSCE PLUS CUATRO GENERACIONES SIN TRANSFERENCIA EN PAPEL", "PEDIGREE_RSCE PLUS RRC (sin genealógica completa) SIN TRANSFERENCIA EN PAPEL", "PEDIGREE_RSCE PLUS RRC CON TRANSFERENCIA", "PEDIGREE_RSCE PLUS TRES GENERACIONES CON TRANSFERENCIA", "PEDIGREE_RSCE PLUS TRES GENERACIONES CON TRANSFERENCIA EN PAPEL", "PEDIGREE_RSCE PLUS TRES GENERACIONES SIN TRANSFERENCIA EN PAPEL", "PEDIGREE_RSCE PREMIUM CUATRO GENERACIONES CON TRANSFERENCIA", "PEDIGREE_RSCE PREMIUM CUATRO GENERACIONES CON TRANSFERENCIA EN PAPEL", "PEDIGREE_RSCE PREMIUM CUATRO GENERACIONES SIN TRANSFERENCIA", "PEDIGREE_RSCE PREMIUM CUATRO GENERACIONES SIN TRANSFERENCIA EN PAPEL", "PEDIGREE_RSCE PREMIUM RRC (sin genealógica completa) CON TRANSFERENCIA", "PEDIGREE_RSCE PREMIUM RRC (sin genealógica completa) CON TRANSFERENCIA EN PAPEL", "PEDIGREE_RSCE PREMIUM RRC (sin genealógica completa) SIN TRANSFERENCIA", "PEDIGREE_RSCE PREMIUM TRES GENERACIONES CON TRANSFERENCIA", "PEDIGREE_RSCE PREMIUM TRES GENERACIONES CON TRANSFERENCIA EN PAPEL", "PEDIGREE_RSCE PREMIUM TRES GENERACIONES SIN TRANSFERENCIA EN PAPEL", "PEDIGREE_RSCE PREMIUN 3 GENERACIONES SIN TRANSFERENCIA", "PLUS ENVÍO CARTILLA POR MENSAJERÍA (hasta un máximo de 10 cartillas por guía)", "PLUS ENVÍO CARTILLA POR MENSAJERÍA (hasta un máximo de 10 cartillas por propietario)", "PLUS POR TRAMITACIÓN URGENTE DE CAMADAS, PEDIGREES Y PEDIGREES DE EXPORTACIÓN", "POR CADA ANOTACIÓN DE INFORME ADN O INFORME DE DISPLASIA EN BASE DE DATOS", "POR CADA ANOTACIÓN EN BASE DE DATOS DE PRUEBA GENÉTICA, INFORME DE ADN O INFORME DE DISPLASIA", "POR PERRO INSCRITO EN CADA PRUEBA CON CAC / CACT", "PRUEBA ADN / PRUEBAS PATERNIDAD, CON ANOTACIÓN EN BASE DE DATOS, ACOGIÉNDOSE AL CONVENIO RSCE – HISPALAB (por perro)", "PRUEBA ADN/PATERNIDAD Y ANOTACIÓN EN BASE DE DATOS, SEGÚN CONVENIO RSCE – HISPALAB (por perro)", "PRUEBA ADN/PATERNIDAD Y ANOTACIÓN EN BASE DE DATOS-CONVENIO RSCE – HISPALAB (por perro) RAZAS ESPAÑOLAS VULNERABLES", "RECARGO 100% (más de 6 meses y menos de 9 meses)  Reglamento L.O.E.", "RECARGO 100% (más de 6 meses y menos de 9) Art. 6.)13 Reglamento L.O.E.", "RECARGO 100% EN INSCRIPCION CACHORRO (más de 6 meses y menos de 9 meses de edad) Reglamento LOE)", "RECARGO 100% EN INSCRIPCIÓN CACHORRO (más de 6 meses y menos de 9 meses de edad)", "RECARGO 100% EN INSCRIPCIÓN CACHORRO (más de 6 meses y menos de 9 meses de edad) Art. 6.13 Reglamento L.O.E.", "RECARGO 200% (más de 9 meses, menos de 12 meses) Reglamento L.O.E.", "RECARGO 200% (más de 9 meses, menos de 12) Art. 6.)13 Reglamento L.O.E.", "RECARGO 200% EN INSCRIPCION CACHORRO (más de 9 meses y menos de 12 meses de edad)  Reglamento LOE)", "RECARGO 200% EN INSCRIPCIÓN CACHORRO (más de 9 meses y menos de 12 meses de edad)", "RECARGO 200% EN INSCRIPCIÓN CACHORRO (más de 9 meses y menos de 12 meses de edad) Art. 6.13 Reglamento L.O.E.", "RECARGO 300% EN INSCRIPCION CACHORRO (más de 12 meses y menos de 18 meses de edad) Reglamento LOE)", "RECARGO 300% EN INSCRIPCIÓN CACHORRO (más de 12 meses y menos de 18 meses de edad)", "RECARGO 300% EN INSCRIPCIÓN CACHORRO (más de 12 meses y menos de 18 meses de edad) Art. 6.13 Reglamento L.O.E.", "RECARGO POR INSCRIPCIÓN DE CACHORRO ACCESS LBO/ RBR con más de 6 meses y menos de 9 meses de edad", "RECARGO POR INSCRIPCIÓN DE CACHORRO ACCESS LBO/RBR con más de 12 meses y menos de 18 meses de edad", "RECARGO POR INSCRIPCIÓN DE CACHORRO ACCESS LBO/RBR con más de 6 meses y menos de 9 meses de edad", "RECARGO POR INSCRIPCIÓN DE CACHORRO ACCESS LBO/RBR con más de 9 meses y menos de 12 meses de edad", "RECARGO POR INSCRIPCIÓN DE CACHORRO PREMIUM LOE/RRC con más de 12 meses y menos de 18 meses de edad", "RECARGO POR INSCRIPCIÓN DE CACHORRO PREMIUM LOE/RRC con más de 6 meses y menos de 9 meses de edad", "RECARGO POR INSCRIPCIÓN DE CACHORRO PREMIUM LOE/RRC con más de 9 meses y menos de 12 meses de edad", "RECARGO POR INSCRIPCIÓN DE CACHORRO con más de 12 meses y menos de 18 meses de edad", "RECARGO POR INSCRIPCIÓN DE CACHORRO con más de 6 meses y menos de 9 meses de edad", "RECARGO POR INSCRIPCIÓN DE CACHORRO con más de 9 meses y menos de 12 meses de edad", "RECTIFICACION AFIJO", "RECTIFICACIÓN DE AFIJO", "RECURSO AL DIAGNOSTICO DE DISPLASIA", "RECURSO AL DIAGNÓSTICO DE DISPLASIA", "RECURSO COMISIÓN LIBRO DE ORÍGENES ESPAÑOL", "REGISTRO INCIAL DE RAZA", "REGISTRO INICIAL DE RAZA", "REGISTRO INICIAL GRUPO ÉTNICO", "REGISTRO INICIAL RAZAS ESPAÑOLAS", "REGISTRO INICIAL RAZAS ESPAÑOLAS VULNERABLES", "REGISTRO INICIAL RESTO DE RAZAS", "RENOVACIÓN ANUAL LICENCIA", "RENOVACIÓN ANUAL LICIENCIA", "SIN DESCRIPCIÓN (tasa fija 0,25€)", "SOLICITUD AFIJO", "SOLICITUD DE AFIJO", "TRAMITACION TITULOS FCI", "TRAMITACION URGENTE  CARTILLA DE ASISTENTE (exclusivamente a través de las oficinas de la RSCE)", "TRAMITACION URGENTE CARTILLAS DE PRUEBAS DEPORTIVAS (exclusivamente a través de las oficinas de la RSCE)", "TRAMITACION URGENTE CERTIFICADOS DE COLA CORTA (se realizará exclusivamente a través de las oficinas de la RSCE)", "TRAMITACION URGENTE CERTIFICADOS DE TRABAJO (se realizará exclusivamente a través de las oficinas de la RSCE)", "TRAMITACION URGENTE DE CAMADAS Y PEDIGREES (exclusivamente a través de las oficinas de la RSCE)", "TRAMITACIÓN TITULOS F.C.I.", "TRAMITACIÓN TITULOS FCI", "TRAMITACIÓN TÍTULOS FCI", "TRAMITACIÓN URGENTE DE CARTILLAS DE ASISTENTE", "TRAMITACIÓN URGENTE DE CARTILLAS DE PRUEBAS DEPORTIVAS", "TRAMITACIÓN URGENTE DE CERTIFICADOS DE COLA CORTA", "TRAMITACIÓN URGENTE DE CERTIFICADOS DE TRABAJO", "TRAMITACIÓN URGENTE DE INSCRIPCIONES EN LOE/RRC, PEDIGRÍES Y TRANSFERENCIAS DE PROPIEDAD", "TRAMITACIÓN URGENTE DE PEDIGRÍES, TRANSFERENCIAS DE PROPIEDAD E INSCRIPCIONES EN LOE/RRC", "TRAMITACIÓN VALORACIÓN DEL GRADO DE DISPLASIA DE CADERA", "TRAMITACIÓN VALORACIÓN DEL GRADO DE DISPLASIA DE CODO", "TRAMITACIÓN VALORACIÓN DEL GRADO DE DISPLASIA DE CODOS", "TRANSFERENCIA DE PROPIEDAD EN PEDIGREE, REGISTRO INICIAL O PERRO IMPORTADO", "TRANSFERENCIA DE PROPIEDAD GRUPOS ETNICOS", "TRANSFERENCIA DE PROPIEDAD REGISTRO INICIAL O PERRO IMPORTADO"],
"categories": ["AFIJOS", "AGILITY", "CAMPO Y TRABAJO (MUESTRA, SPANIELS, RETRIEVERS, TECKEL, TERRIER, RASTRO)", "DISPLASIA", "DUPLICADOS DE PEDIGRÍES", "IDENTIFICACIÓN GENÉTICA", "IMPRESOS", "INSCRIPCIONES", "INSCRIPCIONES ACCESS LBO/RBR", "INSCRIPCIONES EN EL LOE / RRC", "INSCRIPCIONES PREMIUM LOE/RRC", "MEJORA DE ACCESS A PREMIUM", "MUESTRA, RASTRO Y MADRIGUERA", "OTRAS INSCRIPCIONES", "OTROS SERVICIOS", "PEDIGRÍES ACCESS LBO/RBR", "PEDIGRÍES DE EXPORTACIÓN", "PEDIGRÍES PLUS", "PEDIGRÍES PREMIUM LOE/RRC", "PEDIGRÍES Y TRANSFERENCIAS DE PROPIEDAD", "PLUS POR TRAMITACIÓN URGENTE", "REGISTROS INICIALES Y CONFIRMACIONES DE RAZA", "SALUD DEL PERRO", "SOCIOS Y ABONADOS", "Sin categorizar", "TRABAJO (IGP / IGP-IFH / OBEDIENCIA / MONDIORING)"],
"category_by_product": {"1ª CARTILLA": "Sin categorizar", "1ª CARTILLA PERROS DE RASTRO DEL GRUPO 6º": "CAMPO Y TRABAJO (MUESTRA, SPANIELS, RETRIEVERS, TECKEL, TERRIER, RASTRO)", "2ª CARTILLA": "Sin categorizar", "2ª CARTILLA PERROS DE RASTRO DEL GRUPO 6º": "CAMPO Y TRABAJO (MUESTRA, SPANIELS, RETRIEVERS, TECKEL, TERRIER, RASTRO)", "3ª CARTILLA": "Sin categorizar", "3ª CARTILLA PERROS DE RASTRO DEL GRUPO 6º": "CAMPO Y TRABAJO (MUESTRA, SPANIELS, RETRIEVERS, TECKEL, TERRIER, RASTRO)", "3ª MEDICION EJEMPLARES PARA DETERMINAR CATEGORIA DE PARTICIPACIÓN (según reglamento)": "Sin categorizar", "3ª MEDICIÓN EJEMPLARES PARA DETERMINAR CATEGORIA DE PARTICIPACIÓN (según Reglamento)": "Sin categorizar", "3ª MEDICIÓN EJEMPLARES PARA DETERMINAR CATEGORÍA DE PARTICIPACIÓN (según Reglamento)": "AGILITY", "4ª CARTILLA Y SUCESIVAS HASTA EL NÚMERO MÁXIMO DE PERROS QUE COMPONEN UNA JAURÍA SEGÚN EL REGLAMENTO": "Sin categorizar", "4ª CARTILLA Y SUCESIVAS HASTA EL NÚMERO MÁXIMO DE PERROS QUE PUEDAN COMPONER UNA JAURÍA (según Reglamento)": "CAMPO Y TRABAJO (MUESTRA, SPANIELS, RETRIEVERS, TECKEL, TERRIER, RASTRO)", "ANALÍTICA IDENTIFICACIÓN GENÉTICA CANINA A.D.N. / PRUEBAS DE PARTERNIDAD (por perro) - SALIVA": "Sin categorizar", "ANALÍTICA IDENTIFICACIÓN GENÉTICA CANINA A.D.N. / PRUEBAS DE PARTERNIDAD (por perro) - SANGRE": "Sin categorizar", "ANALÍTICA IDENTIFICACIÓN GENÉTICA CANINA A.D.N. / PRUEBAS DE PATERNIDAD (por perro) / SALIVA": "Sin categorizar", "ANALÍTICA IDENTIFICACIÓN GENÉTICA CANINA A.D.N. / PRUEBAS DE PATERNIDAD (por perro) / SANGRE": "Sin categorizar", "ANALÍTICA IDENTIFICACIÓN GENÉTICA CANINA ADN / PRUEBAS DE PATERNIDAD (por perro)": "SALUD DEL PERRO", "ANALÍTICA IDENTIFICACIÓN GENÉTICA CANINA ADN / PRUEBAS DE PATERNIDAD (por perro) / SALIVA": "IDENTIFICACIÓN GENÉTICA", "ANALÍTICA IDENTIFICACIÓN GENÉTICA CANINA ADN / PRUEBAS DE PATERNIDAD (por perro) / SANGRE": "IDENTIFICACIÓN GENÉTICA", "ANOTACIÓN DE TÍTULOS": "OTROS SERVICIOS", "ANOTACIÓN EN BASE DE DATOS DE PRUEBA ADN SIN ACOGERSE AL CONVENIO RSCE – HISPALAB (por perro)": "SALUD DEL PERRO", "ANOTACIÓN EN BASE DE DATOS DE PRUEBA GENÉTICA O DE DISPLASIA (por prueba)": "SALUD DEL PERRO", "ANOTACIÓN EN BASE DE DATOS PRUEBA ADN": "SALUD DEL PERRO", "ANOTACIÓN PRUEBA DE DISPLASIA": "SALUD DEL PERRO", "BAJA DE UN PERRO EN EL L.O.E. / R.R.C. (para su posterior inscripción en otros libros genealógicos)": "Sin categorizar", "BAJA DE UN PERRO EN EL L.O.E./R.R.C.": "Sin categorizar", "BAJA DE UN PERRO EN EL L.O.E./R.R.C. (para su posterior inscripción de otros libros genealógicos)": "Sin categorizar", "BAJA DE UN PERRO EN EL LOE/RRC (para su posterior inscripción de otros libros genealógicos)": "INSCRIPCIONES", "CAMBIO PEDIGREE CUATRO GENERACIONES A PEDIGREE ORO SIN TRANSFERENCIA DE PROPIEDAD": "Sin categorizar", "CAMBIO PEDIGREE TRES GENERACIONES A PEDIGREE ORO SIN TRANSFERENCIA DE PROPIEDAD": "Sin categorizar", "CARTILLA ASISTENTE": "TRABAJO (IGP / IGP-IFH / OBEDIENCIA / MONDIORING)", "CARTILLA DE ASISTENTE": "Sin categorizar", "CARTILLA DE PRUEBAS DEPORTIVAS DE  CAZA": "Sin categorizar", "CARTILLA DE PRUEBAS DEPORTIVAS DE AGILITY": "AGILITY", "CARTILLA DE PRUEBAS DEPORTIVAS DE CAZA": "MUESTRA, RASTRO Y MADRIGUERA", "CARTILLA DE PRUEBAS DEPORTIVAS DE TRABAJO": "TRABAJO (IGP / IGP-IFH / OBEDIENCIA / MONDIORING)", "CARTILLA DE PRUEBAS DEPORTIVAS DE TRABAJO PARA PERROS SIN PEDIGREE": "Sin categorizar", "CARTILLA DE PRUEBAS DEPORTIVAS PARA PERROS SIN PEDIGREE": "TRABAJO (IGP / IGP-IFH / OBEDIENCIA / MONDIORING)", "CARTILLA PARA PRUEBAS DE CAMPO": "CAMPO Y TRABAJO (MUESTRA, SPANIELS, RETRIEVERS, TECKEL, TERRIER, RASTRO)", "CARTILLA PARA PRUEBAS DEPORTIVAS DE CAMPO": "Sin categorizar", "CARTILLA PARA PRUEBAS DEPORTIVAS POLIVALENTES - PERRO DE AGUA ESPAÑOL": "TRABAJO (IGP / IGP-IFH / OBEDIENCIA / MONDIORING)", "CERTIFICADO  DE COLA CORTA": "Sin categorizar", "CERTIFICADO DE COLA CORTA": "SALUD DEL PERRO", "CERTIFICADO DE TRABAJO": "TRABAJO (IGP / IGP-IFH / OBEDIENCIA / MONDIORING)", "CERTIFICADO DE TRABAJO PERROS DE MUESTRA RASTRO Y MADRIGUERA": "Sin categorizar", "CERTIFICADO DE TRABAJO PERROS DE MUESTRA, RASTRO Y MADRIGUERA": "CAMPO Y TRABAJO (MUESTRA, SPANIELS, RETRIEVERS, TECKEL, TERRIER, RASTRO)", "CERTIFICADO INTERNACIONAL DE DISPLASIA": "SALUD DEL PERRO", "CESIÓN TEMPORAL DE PROPIEDAD DE LA HEMBRA REPRODUCTORA": "PEDIGRÍES Y TRANSFERENCIAS DE PROPIEDAD", "CESIÓN TEMPORAL DE PROPIEDAD DE LOS REPRODUCTORES": "Sin categorizar", "CONFIRMACION DE RAZA (PERROS RAZAS ESPAÑOLAS)": "Sin categorizar", "CONFIRMACION DE RAZA (perros de razas españolas)": "Sin categorizar", "CONFIRMACIÓN DE RAZA (PERROS GRUPOS ÉTINICOS)": "Sin categorizar", "CONFIRMACIÓN DE RAZA (perros de razas españolas)": "INSCRIPCIONES", "CUOTA ABONADO": "SOCIOS Y ABONADOS", "CUOTA ABONO JOVEN": "SOCIOS Y ABONADOS", "CUOTA ANUAL CLUB AGILITY": "AGILITY", "CUOTA ANUAL CLUB DE AGILITY": "Sin categorizar", "CUOTA ANUAL GRUPO DE TRABAJO": "TRABAJO (IGP / IGP-IFH / OBEDIENCIA / MONDIORING)", "CUOTA ANUAL MULTIDISCIPLINAR": "TRABAJO (IGP / IGP-IFH / OBEDIENCIA / MONDIORING)", "CUOTA ANUAL SOCIO": "SOCIOS Y ABONADOS", "CUOTA INICIAL SOCIO (incluida la cuota del primer año natural)": "SOCIOS Y ABONADOS", "CUOTA INICIAL SOCIO, incluida la cuota del primer año natural (260 + 30)": "Sin categorizar", "DUPLICADO AFIJO": "Sin categorizar", "DUPLICADO DE AFIJO": "AFIJOS", "DUPLICADO DE PEDIGREE CUATRO GENERACIONES": "PEDIGRÍES Y TRANSFERENCIAS DE PROPIEDAD", "DUPLICADO DE PEDIGREE TRES GENERACIONES": "PEDIGRÍES Y TRANSFERENCIAS DE PROPIEDAD", "DUPLICADO EXPORT PEDIGREE CUATRO GENERACIONES": "PEDIGRÍES Y TRANSFERENCIAS DE PROPIEDAD", "DUPLICADO EXPORT PEDIGREE TRES GENERACIONES": "PEDIGRÍES Y TRANSFERENCIAS DE PROPIEDAD", "DUPLICADO JUSTIFICANTE DE INSCRIPCIÓN": "INSCRIPCIONES", "DUPLICADO PEDIGREE_RSCE": "Sin categorizar", "DUPLICADO PEDIGREE_RSCE DE EXPORTACIÓN 3 GENERACIONES": "Sin categorizar", "DUPLICADO PEDIGREE_RSCE DE EXPORTACIÓN 4 GENERACIONES": "Sin categorizar", "DUPLICADO PEDIGREE_RSCE DE EXPORTACIÓN CUATRO GENERACIONES EN PAPEL": "DUPLICADOS DE PEDIGRÍES", "DUPLICADO PEDIGREE_RSCE DE EXPORTACIÓN TRES GENERACIONES EN PAPEL": "DUPLICADOS DE PEDIGRÍES", "DUPLICADO PEDIGREE_RSCE EN PAPEL": "DUPLICADOS DE PEDIGRÍES", "EDIGREE_RSCE PREMIUM TRES GENERACIONES SIN TRANSFERENCIA": "Sin categorizar", "EXCEPCION, RECARGO 300% (más de 12 meses y menos de 18)  Art, 5.k) Reglamento L.O.E.": "Sin categorizar", "EXCEPCION: RECARGO 300% (más de 12 meses y menos de 18 meses)  Reglamento L.O.E.": "Sin categorizar", "EXPEDICIÓN DE INFORMES (precio por folio impreso)": "OTROS SERVICIOS", "EXPEDICIÓN TITULOS DE CAMPEONES": "OTROS SERVICIOS", "EXPEDICIÓN TITULOS LATIN CHAMPION": "OTROS SERVICIOS", "EXPEDICIÓN TÍTULOS \"LATIN CHAMPION\"": "OTROS SERVICIOS", "EXPEDICIÓN TÍTULOS DE CAMPEONES": "OTROS SERVICIOS", "EXPEDICIÓN TÍTULOS “LATIN CHAMPION”": "Sin categorizar", "FORMULARIO IDENTIFICACIÓN (por cachorro al notificar nacimiento)": "INSCRIPCIONES", "FORMULARIO IDENTIFICACIÓN (por cachorro al notificar nacimiento) EN ORIGEN": "Sin categorizar", "FORMULARIO IDENTIFICACIÓN (por cachorro al notificar nacimiento) RSCE": "Sin categorizar", "IMPRESO ALTA CAMADA": "Sin categorizar", "IMPRESO ALTA DE CAMADA": "INSCRIPCIONES", "IMPRESO ALTA DE CAMADA (GRUPOS ÉTNICOS)": "Sin categorizar", "IMPRESO ALTA DE CAMADA (PERROS DE RAZA)": "Sin categorizar", "IMPRESO DIPLOMA DE INICIACIÓN (original y 3 copias)": "CAMPO Y TRABAJO (MUESTRA, SPANIELS, RETRIEVERS, TECKEL, TERRIER, RASTRO)", "IMPRESO HOJA DE CALIFICACIÓN – PRUEBAS PERRO DE AGUA ESPAÑOL": "TRABAJO (IGP / IGP-IFH / OBEDIENCIA / MONDIORING)", "IMPRESO PARA PRUEBAS CACT - CACIT": "Sin categorizar", "IMPRESO PARA PRUEBAS DE C.A.C.T. - C.A.C.I.T.": "Sin categorizar", "IMPRESO PARA PRUEBAS DE CACT – CACIT": "CAMPO Y TRABAJO (MUESTRA, SPANIELS, RETRIEVERS, TECKEL, TERRIER, RASTRO)", "IMPRESO PRUEBAS APTITUDES NATURALES (original y 3 copias)": "CAMPO Y TRABAJO (MUESTRA, SPANIELS, RETRIEVERS, TECKEL, TERRIER, RASTRO)", "INFORMES SOLICITADOS A LA R.S.C.E. (precio por folio impreso)": "Sin categorizar", "INFORMES SOLICITADOS A LA RSCE (precio por folio impreso": "Sin categorizar", "INFORMES SOLICITADOS A LA RSCE (precio por folio impreso)": "IMPRESOS", "INSCRIPCION DE OTROS LIBROS GENEALOGICOS (NO ADMITE PLUS DE URGENCIA)": "Sin categorizar", "INSCRIPCION PERROS DE OTROS LIBROS GENEALÓGICOS (ESTE TRÁMITE NO ADMITE PLUS DE URGENCIA)": "Sin categorizar", "INSCRIPCIÓN CACHORRO": "INSCRIPCIONES", "INSCRIPCIÓN CACHORRO ACCESS LBO/RBR": "INSCRIPCIONES ACCESS LBO/RBR", "INSCRIPCIÓN CACHORRO DE RAZAS ESPAÑOLAS BONIFICADAS": "INSCRIPCIONES", "INSCRIPCIÓN CACHORRO EN EL REGISTRO DE GRUPOS ÉTNICOS": "INSCRIPCIONES", "INSCRIPCIÓN CACHORRO PREMIUM LOE/RRC": "INSCRIPCIONES PREMIUM LOE/RRC", "INSCRIPCIÓN CACHORRO RAZAS ESPAÑOLAS BONIFICADAS ( Del 01/05/2023 al 30/04/2024)": "Sin categorizar", "INSCRIPCIÓN CACHORRO RAZAS ESPAÑOLAS BONIFICADAS ( Del 01/05/2024 al 30/04/2025)": "Sin categorizar", "INSCRIPCIÓN IMPORTADOS": "INSCRIPCIONES", "INSCRIPCIÓN PERRO con más de 18 meses aportando prueba ADN progenitores y huella genética de compatibilidad": "INSCRIPCIONES", "INSCRIPCIÓN PERROS DE OTROS LIBROS GENEALÓGICOS": "INSCRIPCIONES", "INSCRIPCIÓN PERROS DE OTROS LIBROS GENEALÓGICOS - ESTE TRÁMITE NO ADMITE PLUS DE URGENCIA": "Sin categorizar", "INSCRIPCIÓN PERROS PROCEDENTES DE OTROS LIBROS GENEALÓGICOS": "INSCRIPCIONES", "INSCRIPCIÓN PERROS PROCEDENTES DE OTROS LIBROS GENEALÓGICOS (ESTE TRÁMITE NO ADMITE PLUS DE URGENCIA)": "Sin categorizar", "LICENCIA INCIAL": "Sin categorizar", "LICENCIA INICIAL": "TRABAJO (IGP / IGP-IFH / OBEDIENCIA / MONDIORING)", "MEJORA A PEDIGREE_RSCE PLUS CUATRO GENERACIONES SIN TRANSFERENCIA": "Sin categorizar", "MEJORA A PEDIGREE_RSCE PLUS RRC (sin genealogía completa) CON TRANSFERENCIA": "Sin categorizar", "MEJORA A PEDIGREE_RSCE PLUS RRC (sin genealógica completa) SIN TRANSFERENCIA": "Sin categorizar", "MEJORA A PEDIGREE_RSCE PLUS TRES GENERACIONES SIN TRANSFERENCIA": "Sin categorizar", "MEJORA DE PEDIGREE_RSCE ACCESS LBO A PEDIGREE_RSCE PREMIUM LOE CUATRO GENERACIONES SIN TRANSFERENCIA": "Sin categorizar", "MEJORA DE PEDIGREE_RSCE ACCESS LBO A PEDIGREE_RSCE PREMIUM LOE CUATRO GENERACIONES SIN TRANSFERENCIA EN PAPEL": "MEJORA DE ACCESS A PREMIUM", "MEJORA DE PEDIGREE_RSCE ACCESS LBO A PEDIGREE_RSCE PREMIUM LOE TRES GENERACIONES SIN TRANSFERENCIA": "Sin categorizar", "MEJORA DE PEDIGREE_RSCE ACCESS LBO A PEDIGREE_RSCE PREMIUM LOE TRES GENERACIONES SIN TRANSFERENCIA EN PAPEL": "MEJORA DE ACCESS A PREMIUM", "MEJORA DE PEDIGREE_RSCE ACCESS RBR A PEDIGREE_RSCE PREMIUM RRC SIN TRANSFERENCIA": "Sin categorizar", "MEJORA DE PEDIGREE_RSCE ACCESS RBR A PEDIGREE_RSCE PREMIUM RRC SIN TRANSFERENCIA EN PAPEL": "MEJORA DE ACCESS A PREMIUM", "NOTIFICACIÓN NACIMIENTO CACHORRO (formulario de identificación)": "Sin categorizar", "OTRAS ANOTACIONES EN EL LOE / RRC / RGE": "OTROS SERVICIOS", "PEDIGREE CON TRANSFERENCIA CUATRO GENERACIONES  (SI CONSTAN EN EL L.O.E.)": "Sin categorizar", "PEDIGREE CON TRANSFERENCIA CUATRO GENERACIONES  (si consta en el L.O.E..)": "Sin categorizar", "PEDIGREE CON TRANSFERENCIA CUATRO GENERACIONES (si la genealogía consta en la base de datos del L.O.E.)": "Sin categorizar", "PEDIGREE CON TRANSFERENCIA CUATRO GENERACIONES (si la genealogía consta en la base de datos del LOE)": "PEDIGRÍES Y TRANSFERENCIAS DE PROPIEDAD", "PEDIGREE CON TRANSFERENCIA TRES GENERACIONES": "PEDIGRÍES Y TRANSFERENCIAS DE PROPIEDAD", "PEDIGREE DE EXPORTACION (4 generaciones)": "Sin categorizar", "PEDIGREE DE EXPORTACIÓN CUATRO GENERACIONES (si la genealogía consta en la base de datos del L.O.E.)": "Sin categorizar", "PEDIGREE DE EXPORTACIÓN CUATRO GENERACIONES (si la genealogía consta en la base de datos del LOE)": "PEDIGRÍES Y TRANSFERENCIAS DE PROPIEDAD", "PEDIGREE DE EXPORTACIÓN TRES GENERACIONES": "PEDIGRÍES Y TRANSFERENCIAS DE PROPIEDAD", "PEDIGREE ORO": "Sin categorizar", "PEDIGREE ORO CON TRANSFERENCIA DE PROPIEDAD": "Sin categorizar", "PEDIGREE ORO SIN TRANSFERENCIA": "Sin categorizar", "PEDIGREE PARA PERROS INSCRITOS EN EL R.R.C. (sin genealógica completa)": "Sin categorizar", "PEDIGREE PARA PERROS INSCRITOS EN EL RRC (sin genealógia completa)": "Sin categorizar", "PEDIGREE PARA PERROS INSCRITOS EN EL RRC (sin genealógica completa)": "PEDIGRÍES Y TRANSFERENCIAS DE PROPIEDAD", "PEDIGREE SIN TRANSFERENCIA": "PEDIGRÍES Y TRANSFERENCIAS DE PROPIEDAD", "PEDIGREE SIN TRANSFERENCIA CUATRO GENERACIONES  (SI CONSTAN EN EL L.O.E.)": "Sin categorizar", "PEDIGREE SIN TRANSFERENCIA CUATRO GENERACIONES  (si consta en el  L.O.E.)": "Sin categorizar", "PEDIGREE SIN TRANSFERENCIA CUATRO GENERACIONES (Si la genealogía consta en la base de datos del LOE)": "Sin categorizar", "PEDIGREE SIN TRANSFERENCIA CUATRO GENERACIONES (si la genealogía consta en la base de datos del L.O.E.)": "Sin categorizar", "PEDIGREE SIN TRANSFERENCIA CUATRO GENERACIONES (si la genealogía consta en la base de datos del LOE)": "PEDIGRÍES Y TRANSFERENCIAS DE PROPIEDAD", "PEDIGREE_RSCE ACCESS LBO CON TRANSFERENCIA": "Sin categorizar", "PEDIGREE_RSCE ACCESS LBO SIN TRANSFERENCIA": "Sin categorizar", "PEDIGREE_RSCE ACCESS RBR CON TRANSFERENCIA": "Sin categorizar", "PEDIGREE_RSCE ACCESS RBR CON TRANSFERENCIA EN PAPEL": "PEDIGRÍES ACCESS LBO/RBR", "PEDIGREE_RSCE ACCESS RBR SIN TRANSFERENCIA": "Sin categorizar", "PEDIGREE_RSCE ACCESS SIN TRANSFERENCIA EN PAPEL": "PEDIGRÍES ACCESS LBO/RBR", "PEDIGREE_RSCE ACCESS TRES GENERACIONES CON TRANSFERENCIA EN PAPEL": "PEDIGRÍES ACCESS LBO/RBR", "PEDIGREE_RSCE DE EXPORTACION 3 GENERACIONES": "Sin categorizar", "PEDIGREE_RSCE DE EXPORTACION 4 GENERACIONES": "Sin categorizar", "PEDIGREE_RSCE DE EXPORTACIÓN CUATRO GENERACIONES EN PAPEL": "PEDIGRÍES DE EXPORTACIÓN", "PEDIGREE_RSCE DE EXPORTACIÓN TRES GENERACIONES EN PAPEL": "PEDIGRÍES DE EXPORTACIÓN", "PEDIGREE_RSCE PLUS CUATRO GENERACIONES CON TRANSFERENCIA": "Sin categorizar", "PEDIGREE_RSCE PLUS CUATRO GENERACIONES CON TRANSFERENCIA EN PAPEL": "PEDIGRÍES PLUS", "PEDIGREE_RSCE PLUS CUATRO GENERACIONES SIN TRANSFERENCIA EN PAPEL": "PEDIGRÍES PLUS", "PEDIGREE_RSCE PLUS RRC (sin genealógica completa) SIN TRANSFERENCIA EN PAPEL": "PEDIGRÍES PLUS", "PEDIGREE_RSCE PLUS RRC CON TRANSFERENCIA": "Sin categorizar", "PEDIGREE_RSCE PLUS TRES GENERACIONES CON TRANSFERENCIA": "Sin categorizar", "PEDIGREE_RSCE PLUS TRES GENERACIONES CON TRANSFERENCIA EN PAPEL": "PEDIGRÍES PLUS", "PEDIGREE_RSCE PLUS TRES GENERACIONES SIN TRANSFERENCIA EN PAPEL": "PEDIGRÍES PLUS", "PEDIGREE_RSCE PREMIUM CUATRO GENERACIONES CON TRANSFERENCIA": "Sin categorizar", "PEDIGREE_RSCE PREMIUM CUATRO GENERACIONES CON TRANSFERENCIA EN PAPEL": "PEDIGRÍES PREMIUM LOE/RRC", "PEDIGREE_RSCE PREMIUM CUATRO GENERACIONES SIN TRANSFERENCIA": "Sin categorizar", "PEDIGREE_RSCE PREMIUM CUATRO GENERACIONES SIN TRANSFERENCIA EN PAPEL": "PEDIGRÍES PREMIUM LOE/RRC", "PEDIGREE_RSCE PREMIUM RRC (sin genealógica completa) CON TRANSFERENCIA": "Sin categorizar", "PEDIGREE_RSCE PREMIUM RRC (sin genealógica completa) CON TRANSFERENCIA EN PAPEL": "PEDIGRÍES PREMIUM LOE/RRC", "PEDIGREE_RSCE PREMIUM RRC (sin genealógica completa) SIN TRANSFERENCIA": "Sin categorizar", "PEDIGREE_RSCE PREMIUM TRES GENERACIONES CON TRANSFERENCIA": "Sin categorizar", "PEDIGREE_RSCE PREMIUM TRES GENERACIONES CON TRANSFERENCIA EN PAPEL": "PEDIGRÍES PREMIUM LOE/RRC", "PEDIGREE_RSCE PREMIUM TRES GENERACIONES SIN TRANSFERENCIA EN PAPEL": "PEDIGRÍES PREMIUM LOE/RRC", "PEDIGREE_RSCE PREMIUN 3 GENERACIONES SIN TRANSFERENCIA": "Sin categorizar", "PLUS ENVÍO CARTILLA POR MENSAJERÍA (hasta un máximo de 10 cartillas por guía)": "TRABAJO (IGP / IGP-IFH / OBEDIENCIA / MONDIORING)", "PLUS ENVÍO CARTILLA POR MENSAJERÍA (hasta un máximo de 10 cartillas por propietario)": "CAMPO Y TRABAJO (MUESTRA, SPANIELS, RETRIEVERS, TECKEL, TERRIER, RASTRO)", "PLUS POR TRAMITACIÓN URGENTE DE CAMADAS, PEDIGREES Y PEDIGREES DE EXPORTACIÓN": "Sin categorizar", "POR CADA ANOTACIÓN DE INFORME ADN O INFORME DE DISPLASIA EN BASE DE DATOS": "Sin categorizar", "POR CADA ANOTACIÓN EN BASE DE DATOS DE PRUEBA GENÉTICA, INFORME DE ADN O INFORME DE DISPLASIA": "SALUD DEL PERRO", "POR PERRO INSCRITO EN CADA PRUEBA CON CAC / CACT": "Sin categorizar", "PRUEBA ADN / PRUEBAS PATERNIDAD, CON ANOTACIÓN EN BASE DE DATOS, ACOGIÉNDOSE AL CONVENIO RSCE – HISPALAB (por perro)": "SALUD DEL PERRO", "PRUEBA ADN/PATERNIDAD Y ANOTACIÓN EN BASE DE DATOS, SEGÚN CONVENIO RSCE – HISPALAB (por perro)": "SALUD DEL PERRO", "PRUEBA ADN/PATERNIDAD Y ANOTACIÓN EN BASE DE DATOS-CONVENIO RSCE – HISPALAB (por perro) RAZAS ESPAÑOLAS VULNERABLES": "SALUD DEL PERRO", "RECARGO 100% (más de 6 meses y menos de 9 meses)  Reglamento L.O.E.": "Sin categorizar", "RECARGO 100% (más de 6 meses y menos de 9) Art. 6.)13 Reglamento L.O.E.": "Sin categorizar", "RECARGO 100% EN INSCRIPCION CACHORRO (más de 6 meses y menos de 9 meses de edad) Reglamento LOE)": "Sin categorizar", "RECARGO 100% EN INSCRIPCIÓN CACHORRO (más de 6 meses y menos de 9 meses de edad)": "INSCRIPCIONES EN EL LOE / RRC", "RECARGO 100% EN INSCRIPCIÓN CACHORRO (más de 6 meses y menos de 9 meses de edad) Art. 6.13 Reglamento L.O.E.": "Sin categorizar", "RECARGO 200% (más de 9 meses, menos de 12 meses) Reglamento L.O.E.": "Sin categorizar", "RECARGO 200% (más de 9 meses, menos de 12) Art. 6.)13 Reglamento L.O.E.": "Sin categorizar", "RECARGO 200% EN INSCRIPCION CACHORRO (más de 9 meses y menos de 12 meses de edad)  Reglamento LOE)": "Sin categorizar", "RECARGO 200% EN INSCRIPCIÓN CACHORRO (más de 9 meses y menos de 12 meses de edad)": "INSCRIPCIONES EN EL LOE / RRC", "RECARGO 200% EN INSCRIPCIÓN CACHORRO (más de 9 meses y menos de 12 meses de edad) Art. 6.13 Reglamento L.O.E.": "Sin categorizar", "RECARGO 300% EN INSCRIPCION CACHORRO (más de 12 meses y menos de 18 meses de edad) Reglamento LOE)": "Sin categorizar", "RECARGO 300% EN INSCRIPCIÓN CACHORRO (más de 12 meses y menos de 18 meses de edad)": "INSCRIPCIONES EN EL LOE / RRC", "RECARGO 300% EN INSCRIPCIÓN CACHORRO (más de 12 meses y menos de 18 meses de edad) Art. 6.13 Reglamento L.O.E.": "Sin categorizar", "RECARGO POR INSCRIPCIÓN DE CACHORRO ACCESS LBO/ RBR con más de 6 meses y menos de 9 meses de edad": "Sin categorizar", "RECARGO POR INSCRIPCIÓN DE CACHORRO ACCESS LBO/RBR con más de 12 meses y menos de 18 meses de edad": "INSCRIPCIONES ACCESS LBO/RBR", "RECARGO POR INSCRIPCIÓN DE CACHORRO ACCESS LBO/RBR con más de 6 meses y menos de 9 meses de edad": "INSCRIPCIONES ACCESS LBO/RBR", "RECARGO POR INSCRIPCIÓN DE CACHORRO ACCESS LBO/RBR con más de 9 meses y menos de 12 meses de edad": "INSCRIPCIONES ACCESS LBO/RBR", "RECARGO POR INSCRIPCIÓN DE CACHORRO PREMIUM LOE/RRC con más de 12 meses y menos de 18 meses de edad": "INSCRIPCIONES PREMIUM LOE/RRC", "RECARGO POR INSCRIPCIÓN DE CACHORRO PREMIUM LOE/RRC con más de 6 meses y menos de 9 meses de edad": "INSCRIPCIONES PREMIUM LOE/RRC", "RECARGO POR INSCRIPCIÓN DE CACHORRO PREMIUM LOE/RRC con más de 9 meses y menos de 12 meses de edad": "INSCRIPCIONES PREMIUM LOE/RRC", "RECARGO POR INSCRIPCIÓN DE CACHORRO con más de 12 meses y menos de 18 meses de edad": "INSCRIPCIONES", "RECARGO POR INSCRIPCIÓN DE CACHORRO con más de 6 meses y menos de 9 meses de edad": "INSCRIPCIONES", "RECARGO POR INSCRIPCIÓN DE CACHORRO con más de 9 meses y menos de 12 meses de edad": "INSCRIPCIONES", "RECTIFICACION AFIJO": "Sin categorizar", "RECTIFICACIÓN DE AFIJO": "AFIJOS", "RECURSO AL DIAGNOSTICO DE DISPLASIA": "Sin categorizar", "RECURSO AL DIAGNÓSTICO DE DISPLASIA": "SALUD DEL PERRO", "RECURSO COMISIÓN LIBRO DE ORÍGENES ESPAÑOL": "OTROS SERVICIOS", "REGISTRO INCIAL DE RAZA": "Sin categorizar", "REGISTRO INICIAL DE RAZA": "REGISTROS INICIALES Y CONFIRMACIONES DE RAZA", "REGISTRO INICIAL GRUPO ÉTNICO": "INSCRIPCIONES", "REGISTRO INICIAL RAZAS ESPAÑOLAS": "INSCRIPCIONES", "REGISTRO INICIAL RAZAS ESPAÑOLAS VULNERABLES": "INSCRIPCIONES", "REGISTRO INICIAL RESTO DE RAZAS": "INSCRIPCIONES", "RENOVACIÓN ANUAL LICENCIA": "TRABAJO (IGP / IGP-IFH / OBEDIENCIA / MONDIORING)", "RENOVACIÓN ANUAL LICIENCIA": "Sin categorizar", "SIN DESCRIPCIÓN (tasa fija 0,25€)": "Sin categorizar", "SOLICITUD AFIJO": "Sin categorizar", "SOLICITUD DE AFIJO": "AFIJOS", "TRAMITACION TITULOS FCI": "Sin categorizar", "TRAMITACION URGENTE  CARTILLA DE ASISTENTE (exclusivamente a través de las oficinas de la RSCE)": "Sin categorizar", "TRAMITACION URGENTE CARTILLAS DE PRUEBAS DEPORTIVAS (exclusivamente a través de las oficinas de la RSCE)": "Sin categorizar", "TRAMITACION URGENTE CERTIFICADOS DE COLA CORTA (se realizará exclusivamente a través de las oficinas de la RSCE)": "Sin categorizar", "TRAMITACION URGENTE CERTIFICADOS DE TRABAJO (se realizará exclusivamente a través de las oficinas de la RSCE)": "Sin categorizar", "TRAMITACION URGENTE DE CAMADAS Y PEDIGREES (exclusivamente a través de las oficinas de la RSCE)": "Sin categorizar", "TRAMITACIÓN TITULOS F.C.I.": "Sin categorizar", "TRAMITACIÓN TITULOS FCI": "OTROS SERVICIOS", "TRAMITACIÓN TÍTULOS FCI": "OTROS SERVICIOS", "TRAMITACIÓN URGENTE DE CARTILLAS DE ASISTENTE": "PLUS POR TRAMITACIÓN URGENTE", "TRAMITACIÓN URGENTE DE CARTILLAS DE PRUEBAS DEPORTIVAS": "PLUS POR TRAMITACIÓN URGENTE", "TRAMITACIÓN URGENTE DE CERTIFICADOS DE COLA CORTA": "PLUS POR TRAMITACIÓN URGENTE", "TRAMITACIÓN URGENTE DE CERTIFICADOS DE TRABAJO": "PLUS POR TRAMITACIÓN URGENTE", "TRAMITACIÓN URGENTE DE INSCRIPCIONES EN LOE/RRC, PEDIGRÍES Y TRANSFERENCIAS DE PROPIEDAD": "PLUS POR TRAMITACIÓN URGENTE", "TRAMITACIÓN URGENTE DE PEDIGRÍES, TRANSFERENCIAS DE PROPIEDAD E INSCRIPCIONES EN LOE/RRC": "PLUS POR TRAMITACIÓN URGENTE", "TRAMITACIÓN VALORACIÓN DEL GRADO DE DISPLASIA DE CADERA": "SALUD DEL PERRO", "TRAMITACIÓN VALORACIÓN DEL GRADO DE DISPLASIA DE CODO": "SALUD DEL PERRO", "TRAMITACIÓN VALORACIÓN DEL GRADO DE DISPLASIA DE CODOS": "DISPLASIA", "TRANSFERENCIA DE PROPIEDAD EN PEDIGREE, REGISTRO INICIAL O PERRO IMPORTADO": "PEDIGRÍES Y TRANSFERENCIAS DE PROPIEDAD", "TRANSFERENCIA DE PROPIEDAD GRUPOS ETNICOS": "Sin categorizar", "TRANSFERENCIA DE PROPIEDAD REGISTRO INICIAL O PERRO IMPORTADO": "OTRAS INSCRIPCIONES"}}

  export default function RSCEDashboard() {
  const [products, setProducts] = useState(() => [...RSCE_DATA.products]);
  const [categories, setCategories] = useState(() => [...RSCE_DATA.categories]);
  const [data, setData] = useState(() => JSON.parse(JSON.stringify(RSCE_DATA.data)));
  const [years, setYears] = useState(() => [...RSCE_DATA.years]);

  const [query, setQuery] = useState("");
  const [categoryFilter, setCategoryFilter] = useState("Todas");
  const [selected, setSelected] = useState(products[0]);
  const [vatMode, setVatMode] = useState("with_vat"); // 'with_vat' | 'no_vat'
  const [cpiRate, setCpiRate] = useState(0.02);
  const [cpiDraft, setCpiDraft] = useState((0.02 * 100).toFixed(1)); // ← add this line

  const [overrides, setOverrides] = useState({}); // key `${product}::${ct}` -> number

  const [loading, setLoading] = useState(true);
const [saveStatus, setSaveStatus] = useState("idle"); // 'idle' | 'saving' | 'saved' | 'error'
const isFirstRun = useRef(true);

useEffect(() => {
  let cancelled = false;
  (async () => {
    const { data: row, error } = await supabase
      .from("rsce_dataset").select("*").eq("id", 1).maybeSingle();

    if (error) { console.error(error); setLoading(false); return; }

    if (row) {
      if (!cancelled) {
        setProducts(row.products);
        setCategories(row.categories);
        setData(row.data);
      }
    } else {
      // first run ever — seed Supabase from the bundled data
      await supabase.from("rsce_dataset").insert({
        id: 1, products: RSCE_DATA.products,
        categories: RSCE_DATA.categories, data: RSCE_DATA.data,
      });
    }

    const { data: overrideRows } = await supabase.from("rsce_overrides").select("*");
    if (overrideRows && !cancelled) {
      const ov = {};
      overrideRows.forEach((r) => { ov[`${r.product}::${r.client_type}`] = r.value; });
      setOverrides(ov);
    }
    if (!cancelled) setLoading(false);
  })();
  return () => { cancelled = true; };
}, []);



useEffect(() => {
  if (isFirstRun.current) { isFirstRun.current = false; return; }
  if (loading) return;
  setSaveStatus("saving");
  supabase.from("rsce_dataset")
    .upsert({ id: 1, products, categories, data, updated_at: new Date().toISOString() })
    .then(({ error }) => setSaveStatus(error ? "error" : "saved"));
}, [products, categories, data, loading]);

console.log("categoryFilter:", categoryFilter, "| sample category:", data[products[0]]?.category);

const [editYear, setEditYear] = useState(RSCE_DATA.years[RSCE_DATA.years.length - 1]);
  const [showAddProduct, setShowAddProduct] = useState(false);
const [newProductName, setNewProductName] = useState("");
const [newProductCategory, setNewProductCategory] = useState(categories[0] || "Sin categorizar");
const [addingNewCategory, setAddingNewCategory] = useState(false);
const [newCategoryInput, setNewCategoryInput] = useState("");

const handleAddProduct = useCallback(() => {
  const name = newProductName.trim();
  if (!name) return;
  if (data[name]) {
    alert("Ya existe un producto con ese nombre.");
    return;
  }
  const category = addingNewCategory
    ? (newCategoryInput.trim() || "Sin categorizar")
    : newProductCategory;

  setData((prev) => ({
    ...prev,
    [name]: { category, prices: { Member: [], User: [], Canine_Collaborator: [] } },
  }));
  setProducts((prev) => [...prev, name].sort((a, b) => a.localeCompare(b, "es")));
  setCategories((prev) =>
    prev.includes(category) ? prev : [...prev, category].sort((a, b) => a.localeCompare(b, "es"))
  );

  setSelected(name);
  setShowAddProduct(false);
  setNewProductName("");
  setNewCategoryInput("");
  setAddingNewCategory(false);
}, [newProductName, newProductCategory, newCategoryInput, addingNewCategory, data]);


const handleAddYear = useCallback(() => {
  setYears((prev) => {
    const next = Math.max(...prev) + 1;
    return prev.includes(next) ? prev : [...prev, next];
  });
}, []);

const handleRemoveYear = useCallback((yearToRemove) => {
  if (years.length <= 1) return;
  const ok = window.confirm(
    `¿Eliminar el año ${yearToRemove}? Esto borrará cualquier precio introducido para ese año en todos los productos.`
  );
  if (!ok) return;

  setYears((prev) => prev.filter((y) => y !== yearToRemove));
  setData((prev) => {
    const next = {};
    for (const [product, rec] of Object.entries(prev)) {
      const newPrices = {};
      for (const ct of CT_ORDER) {
        newPrices[ct] = (rec.prices[ct] || []).filter((p) => p.year !== yearToRemove);
      }
      next[product] = { ...rec, prices: newPrices };
    }
    return next;
  });
}, [years]);

const updatePrice = useCallback((product, ct, field, rawValue, year) => {
  const val = rawValue === "" ? null : parseFloat(String(rawValue).replace(",", "."));
  setData((prev) => {
    const rec = prev[product];
    if (!rec) return prev;
    const series = rec.prices[ct] || [];
    const idx = series.findIndex((p) => p.year === year);
    const newSeries = idx >= 0
      ? series.map((p, i) => (i === idx ? { ...p, [field]: val } : p))
      : [...series, { year, with_vat: null, no_vat: null, [field]: val }]
          .sort((a, b) => a.year - b.year);
    return { ...prev, [product]: { ...rec, prices: { ...rec.prices, [ct]: newSeries } } };
  });
}, []);

  useEffect(() => {
  setCpiDraft((cpiRate * 100).toFixed(1));
}, [cpiRate]);

  useEffect(() => {
  if (!years.includes(editYear)) {
    setEditYear(years[years.length - 1]);
  }
}, [years, editYear]);

  const filteredProducts = useMemo(() => {
    return products.filter((p) => {
      const matchesQuery = query.trim() === "" || p.toLowerCase().includes(query.trim().toLowerCase());
      const matchesCat = categoryFilter === "Todas" || data[p].category === categoryFilter;
      return matchesQuery && matchesCat;
    });
  }, [query, categoryFilter, products, data]);

  const selectedRecord = data[selected];

  const perTypeStats = useMemo(() => {
    if (!selectedRecord) return {};
    const latestYear = years[years.length - 1];
    const out = {};
    for (const ct of CT_ORDER) {
      const series = selectedRecord.prices[ct] || [];
      const last = valueForYear(series, vatMode, years[years.length - 1]);
      const prev = last ? secondLastNonNull(series, vatMode, last.year) : null;
      const yoy = last && prev ? pctChange(prev[vatMode], last[vatMode]) : null;
      out[ct] = { last, prev, yoy };
    }
    return out;
  }, [selectedRecord, vatMode, years]);

  const crossTypeVariation = useMemo(() => {
    const m = perTypeStats.Member?.last?.[vatMode] ?? null;
    const u = perTypeStats.User?.last?.[vatMode] ?? null;
    const c = perTypeStats.Canine_Collaborator?.last?.[vatMode] ?? null;
    return {
      userVsMember: m && u ? pctChange(m, u) : null,
      collabVsMember: m && c ? pctChange(m, c) : null,
      collabVsUser: u && c ? pctChange(u, c) : null,
    };
  }, [perTypeStats, vatMode]);

  const chartData = useMemo(() => {
    if (!selectedRecord) return [];
    return years.map((y) => {
      const row = { year: y };
      for (const ct of CT_ORDER) {
        const point = (selectedRecord.prices[ct] || []).find((p) => p.year === y);
        row[ct] = point ? point[vatMode] : null;
      }
      return row;
    });
  }, [selectedRecord, years, vatMode]);

  const setOverride = useCallback((ct, value) => {
  const key = `${selected}::${ct}`;
  const numValue = value === "" || value === null ? null : parseFloat(value);

  setOverrides((prev) => {
    const next = { ...prev };
    if (numValue === null || Number.isNaN(numValue)) delete next[key];
    else next[key] = numValue;
    return next;
  });

  setSaveStatus("saving");
  const req = (numValue === null || Number.isNaN(numValue))
    ? supabase.from("rsce_overrides").delete().eq("product", selected).eq("client_type", ct)
    : supabase.from("rsce_overrides").upsert({
        product: selected, client_type: ct, value: numValue,
        updated_at: new Date().toISOString(),
      });

  req.then(({ error }) => setSaveStatus(error ? "error" : "saved"));
}, [selected]);

  const overrideKey = (p, ct) => `${p}::${ct}`;

  const handleExport = useCallback(() => {
    const wb = XLSX.utils.book_new();

    // Sheet 1: raw long-format data
    const rawRows = [["Año", "Producto", "Categoría", "Tipo de Cliente", "Precio con IVA", "Precio sin IVA"]];
    for (const p of products) {
      const rec = data[p];
      for (const ct of CT_ORDER) {
        for (const point of rec.prices[ct]) {
          rawRows.push([point.year, p, rec.category, CT_LABELS[ct], point.with_vat, point.no_vat]);
        }
      }
    }
    const wsRaw = XLSX.utils.aoa_to_sheet(rawRows);
    XLSX.utils.book_append_sheet(wb, wsRaw, "Datos");

    // Sheet 2: summary + forecast snapshot (values, not live formulas)
    const summaryHeader = ["Producto", "Categoría"];
    for (const ct of CT_ORDER) {
      const label = CT_LABELS[ct];
      summaryHeader.push(
        `${label}: Año base`, `${label}: Precio base (€)`,
        `${label}: Variación interanual (%)`,
        `${label}: Previsión IPC (€)`, `${label}: Anulación manual (€)`, `${label}: Precio final (€)`
      );
    }
    const summaryRows = [summaryHeader];
    for (const p of products) {
      const rec = data[p];
      const row = [p, rec.category];
      for (const ct of CT_ORDER) {
        const series = rec.prices[ct] || [];
        const last = lastNonNull(series, vatMode);
        const prev = last ? secondLastNonNull(series, vatMode, last.year) : null;
        const yoy = last && prev ? pctChange(prev[vatMode], last[vatMode]) : null;
        const basePrice = last ? last[vatMode] : null;
        const forecast = basePrice !== null ? Math.round(basePrice * (1 + cpiRate) * 100) / 100 : null;
        const ov = overrides[overrideKey(p, ct)];
        const final = ov !== undefined && !Number.isNaN(ov) ? ov : forecast;
        row.push(
          last ? last.year : "",
          basePrice,
          yoy !== null ? Math.round(yoy * 1000) / 10 : "",
          forecast,
          ov !== undefined ? ov : "",
          final
        );
      }
      summaryRows.push(row);
    }
    const wsSummary = XLSX.utils.aoa_to_sheet(summaryRows);
    XLSX.utils.book_append_sheet(wb, wsSummary, "Resumen_y_Prevision");

    // Sheet 3: assumptions note
    const wsNotes = XLSX.utils.aoa_to_sheet([
      ["Notas de la exportación"],
      [""],
      [`Tasa de IPC utilizada: ${(cpiRate * 100).toFixed(1)}%`],
      [`Modo de precio: ${vatMode === "with_vat" ? "Con IVA" : "Sin IVA"}`],
      [`Fecha de exportación: ${new Date().toLocaleDateString("es-ES")}`],
      [""],
      ["Este archivo es una instantánea de valores calculados en el panel interactivo."],
      ["A diferencia del libro Excel original (RSCE_Price_Analysis.xlsx), estas celdas"],
      ["NO son fórmulas en vivo — reflejan el estado del panel en el momento de exportar,"],
      ["incluyendo cualquier anulación manual introducida en esta sesión."],
    ]);
    XLSX.utils.book_append_sheet(wb, wsNotes, "Notas");

    XLSX.writeFile(wb, `RSCE_Dashboard_Export_${new Date().toISOString().slice(0, 10)}.xlsx`);
  }, [products, data, vatMode, cpiRate, overrides]);

  return (
    <div style={{
      fontFamily: "'Inter', system-ui, sans-serif",
      background: "#F6F3EC",
      minHeight: "100vh",
      color: "#20242C",
    }}>
      {/* Header */}
      <div style={{
        background: "#1C2B45",
        color: "#F6F3EC",
        padding: "20px 28px",
        display: "flex",
        alignItems: "center",
        justifyContent: "space-between",
        borderBottom: "3px solid #B98A3F",
      }}>
        <div style={{ display: "flex", alignItems: "flex-start", gap: 10 }}>
  <div
    style={{
      width: 42,
      height: 42,
      borderRadius: "50%",
      background: "#B98A3F",
      display: "flex",
      alignItems: "center",
      justifyContent: "center",
      flexShrink: 0,
      marginTop: 2,
    }}
  >
    <PawPrint size={22} color="#1C2B45" />
  </div>

  <div
    style={{
      display: "flex",
      flexDirection: "column",
      alignItems: "flex-start",
      justifyContent: "center",
    }}
  >
    <div
      style={{
        fontFamily: "'Georgia', serif",
        fontSize: 20,
        fontWeight: 700,
        lineHeight: 1.1,
        marginBottom: 3,
      }}
    >
      Real Sociedad Canina de España
    </div>

    <div
      style={{
        fontSize: 12.5,
        opacity: 0.75,
        marginLeft: 0,
        paddingLeft: 0,
        textAlign: "left",
        alignSelf: "flex-start",
      }}
    >
      Panel de análisis de tarifas
    </div>
  </div>
</div>
        <div style={{ display: "flex", alignItems: "center", gap: 10 }}>
          <button
            onClick={handleExport}
            style={{
              display: "flex", alignItems: "center", gap: 8,
              background: "#B98A3F", color: "#1C2B45", border: "none",
              padding: "10px 18px", borderRadius: 6, fontWeight: 600, fontSize: 14,
              cursor: "pointer",
            }}
          >
            <Download size={16} /> Exportar a Excel
          </button>
          {saveStatus === "saving" && <Loader size={14} className="animate-spin" style={{ opacity: 0.7, color: "#F6F3EC" }} />}
          {saveStatus === "saved" && <CheckCircle size={14} color="#5C7A5E" />}
          {saveStatus === "error" && <span style={{ fontSize: 11, color: "#A6452E" }}>Error al guardar</span>}
        </div>
      </div>


      <div style={{ display: "flex", maxWidth: 1400, margin: "0 auto" }}>
        {/* Sidebar */}
        <div style={{
          width: 320, flexShrink: 0, borderRight: "1px solid #DDD6C6",
          padding: "20px 16px", background: "#FBFAF6", minHeight: "calc(100vh - 82px)",
        }}>
          <div style={{ position: "relative", marginBottom: 12 }}>
            <Search size={16} style={{ position: "absolute", left: 10, top: 10, opacity: 0.5 }} />
            <input
              value={query}
              onChange={(e) => setQuery(e.target.value)}
              placeholder="Buscar producto..."
              style={{
                width: "100%", padding: "8px 10px 8px 32px", borderRadius: 6,
                border: "1px solid #D4CDBB", fontSize: 13.5, boxSizing: "border-box",
                fontFamily: "inherit",
              }}
            />
          </div>
          <select
            value={categoryFilter}
            onChange={(e) => setCategoryFilter(e.target.value)}
            style={{
              width: "100%", padding: "7px 8px", borderRadius: 6, border: "1px solid #D4CDBB",
              fontSize: 13, marginBottom: 10, fontFamily: "inherit", background: "white", color: "#20242C",
            }}
          >
            <option value="Todas" style={{ color: "#20242C", background: "white" }}>Todas las categorías</option>
            {categories.map((c) => (
              <option key={c} value={c} style={{ color: "#20242C", background: "white" }}>{c}</option>
            ))}
          </select>

          <button
            onClick={() => setShowAddProduct((v) => !v)}
            style={{
              width: "100%", padding: "7px 8px", borderRadius: 6, border: "1px dashed #B98A3F",
              fontSize: 12.5, fontWeight: 600, marginBottom: 14, cursor: "pointer",
              background: "transparent", color: "#8C6B2E",
            }}
          >
            {showAddProduct ? "Cancelar" : "+ Añadir producto"}
          </button>

          {showAddProduct && (
            <div style={{
              background: "#FFFBEA", border: "1px solid #E5DFD1", borderRadius: 8,
              padding: 10, marginBottom: 14,
            }}>
              <input
                value={newProductName}
                onChange={(e) => setNewProductName(e.target.value)}
                placeholder="Nombre del producto"
                style={{
                  width: "100%", padding: "6px 8px", borderRadius: 6, border: "1px solid #D4CDBB",
                  fontSize: 12.5, marginBottom: 8, fontFamily: "inherit", boxSizing: "border-box",
                }}
              />

              {!addingNewCategory ? (
                <select
                  value={newProductCategory}
                  onChange={(e) => {
                    if (e.target.value === "__new__") setAddingNewCategory(true);
                    else setNewProductCategory(e.target.value);
                  }}
                  style={{
                    width: "100%", padding: "6px 8px", borderRadius: 6, border: "1px solid #D4CDBB",
                    fontSize: 12.5, marginBottom: 8, fontFamily: "inherit", background: "white", color: "#20242C",
                  }}
                >
                  {categories.map((c) => (
                    <option key={c} value={c} style={{ color: "#20242C", background: "white" }}>{c}</option>
                  ))}
                  <option value="__new__" style={{ color: "#20242C", background: "white" }}>+ Nueva categoría…</option>
                </select>
              ) : (
                <input
                  value={newCategoryInput}
                  onChange={(e) => setNewCategoryInput(e.target.value)}
                  placeholder="Nombre de la nueva categoría"
                  style={{
                    width: "100%", padding: "6px 8px", borderRadius: 6, border: "1px solid #D4CDBB",
                    fontSize: 12.5, marginBottom: 8, fontFamily: "inherit", boxSizing: "border-box",
                  }}
                />
              )}

              <button
                onClick={handleAddProduct}
                style={{
                  width: "100%", padding: "7px 8px", borderRadius: 6, border: "none",
                  background: "#B98A3F", color: "#1C2B45", fontWeight: 700, fontSize: 12.5,
                  cursor: "pointer",
                }}
              >
                Guardar producto
              </button>
            </div>
          )}

          <div style={{ fontSize: 11.5, opacity: 0.6, marginBottom: 8, fontWeight: 600 }}>
            {filteredProducts.length} PRODUCTOS
          </div>
          <div style={{ maxHeight: "calc(100vh - 250px)", overflowY: "auto" }}>
            {filteredProducts.map((p) => (
              <div
                key={p}
                onClick={() => setSelected(p)}
                style={{
                  padding: "9px 10px",
                  borderRadius: 6,
                  cursor: "pointer",
                  fontSize: 13,
                  marginBottom: 3,
                  lineHeight: 1.35,
                  background: p === selected ? "#1C2B45" : "transparent",
                  color: p === selected ? "#F6F3EC" : "#20242C",

                  textAlign: "left",
                  display: "flex",
                  alignItems: "center",
                  justifyContent: "flex-start",
                  whiteSpace: "normal",
                  wordBreak: "break-word",
}}
              >
                {p}
              </div>
            ))}
          </div>
        </div>

        {/* Main content */}
        <div style={{ flex: 1, padding: "24px 32px", minWidth: 0 }}>
          {selectedRecord && (
            <>
              <div style={{ display: "flex", justifyContent: "space-between", alignItems: "flex-start", marginBottom: 4 }}>
                <div>
                  <div style={{ fontSize: 11, textTransform: "uppercase", letterSpacing: 0.8, color: "#B98A3F", fontWeight: 700 }}>
                    {selectedRecord.category}
                  </div>
                  <h1 style={{ fontFamily: "'Georgia', serif", fontSize: 24, margin: "2px 0 0 0", lineHeight: 1.25 }}>
                    {selected}
                  </h1>
                  
                  
                </div>
                <div style={{ display: "flex", gap: 4, background: "#EFEAE0", borderRadius: 8, padding: 3 }}>
                  <button
                    onClick={() => setVatMode("with_vat")}
                    style={{
                      padding: "6px 14px", borderRadius: 6, border: "none", fontSize: 12.5, fontWeight: 600,
                      cursor: "pointer",
                      background: vatMode === "with_vat" ? "#1C2B45" : "transparent",
                      color: vatMode === "with_vat" ? "#F6F3EC" : "#20242C",
                    }}
                  >Con IVA</button>
                  <button
                    onClick={() => setVatMode("no_vat")}
                    style={{
                      padding: "6px 14px", borderRadius: 6, border: "none", fontSize: 12.5, fontWeight: 600,
                      cursor: "pointer",
                      background: vatMode === "no_vat" ? "#1C2B45" : "transparent",
                      color: vatMode === "no_vat" ? "#F6F3EC" : "#20242C",
                    }}
                  >Sin IVA</button>
                </div>
              </div>

              {/* Stat cards */}
              <div style={{ display: "grid", gridTemplateColumns: "repeat(3, 1fr)", gap: 12, margin: "18px 0" }}>
                {CT_ORDER.map((ct) => {
                  const s = perTypeStats[ct];
                  return (
                    <div key={ct} style={{
                      background: "white", borderRadius: 10, padding: "14px 16px",
                      border: "1px solid #E5DFD1", borderTop: `3px solid ${CT_COLORS[ct]}`,
                    }}>
                      <div style={{ fontSize: 11.5, fontWeight: 700, opacity: 0.65, textTransform: "uppercase", letterSpacing: 0.4 }}>
                        {CT_LABELS[ct]}
                      </div>
                      <div style={{ fontSize: 22, fontWeight: 700, margin: "4px 0 2px 0", fontFamily: "'Georgia', serif" }}>
                        {fmtEUR(s?.last ? s.last[vatMode] : null)}
                      </div>
                      <div style={{ fontSize: 12, opacity: 0.6, marginBottom: 6 }}>
                        {s?.last ? `Año base: ${s.last.year}` : "—"}
                      </div>
                      <div style={{ display: "flex", alignItems: "center", gap: 5, fontSize: 12.5 }}>
                        <TrendIcon v={s?.yoy} />
                        <span>{s?.yoy !== null && s?.yoy !== undefined ? `${fmtPct(s.yoy)} interanual` : "Sin comparación previa"}</span>
                      </div>
                    </div>
                  );
                })}
              </div>

              {/* Chart */}
              <div style={{ background: "white", borderRadius: 10, border: "1px solid #E5DFD1", padding: "18px 20px", marginBottom: 18 }}>
                <div style={{ fontSize: 13, fontWeight: 700, marginBottom: 10, opacity: 0.75 }}>
                  Evolución de precios ({vatMode === "with_vat" ? "con IVA" : "sin IVA"})
                </div>
                <ResponsiveContainer width="100%" height={260}>
                  <LineChart data={chartData} margin={{ top: 5, right: 20, left: 0, bottom: 0 }}>
                    <CartesianGrid strokeDasharray="3 3" stroke="#EEE8DA" />
                    <XAxis dataKey="year" tick={{ fontSize: 12 }} stroke="#8A8474" />
                    <YAxis tick={{ fontSize: 12 }} stroke="#8A8474" width={50} />
                    <Tooltip formatter={(v) => fmtEUR(v)} labelStyle={{ fontWeight: 600 }} />
                    <Legend formatter={(v) => CT_LABELS[v]} wrapperStyle={{ fontSize: 12.5 }} />
                    {CT_ORDER.map((ct) => (
                      <Line
                        key={ct} type="monotone" dataKey={ct} stroke={CT_COLORS[ct]}
                        strokeWidth={2.5} dot={{ r: 3 }} connectNulls={false}
                      />
                    ))}
                  </LineChart>
                </ResponsiveContainer>
              </div>

              {/* Editar precios (año seleccionable) */}
              <div style={{ background: "white", borderRadius: 10, border: "1px solid #E5DFD1", padding: "18px 20px", marginBottom: 18 }}>
                <div style={{ display: "flex", alignItems: "center", justifyContent: "space-between", marginBottom: 10 }}>
                  <div style={{ fontSize: 13, fontWeight: 700, opacity: 0.75 }}>Editar precios</div>
                  <div style={{ display: "flex", alignItems: "center", gap: 8 }}>
                    <button
                      onClick={handleAddYear}
                      title="Crea el siguiente año en el histórico, disponible para todos los productos"
                      style={{
                        padding: "5px 10px", borderRadius: 6, border: "1px dashed #B98A3F",
                        fontSize: 12, fontWeight: 600, cursor: "pointer", background: "transparent",
                        color: "#8C6B2E",
                      }}
                    >
                      + Crear año {Math.max(...years) + 1}
                    </button>
                    <label style={{ fontSize: 12.5, opacity: 0.7 }}>Año:</label>
                    <select
                      value={editYear}
                      onChange={(e) => setEditYear(Number(e.target.value))}
                      style={{
                        padding: "5px 8px", borderRadius: 6, border: "1px solid #D4CDBB",
                        fontSize: 13, fontFamily: "inherit", background: "white", color: "#20242C",
                      }}
                    >
                      {years.map((y) => (
                        <option key={y} value={y} style={{ color: "#20242C", background: "white" }}>
                          {y}{y === years[years.length - 1] ? " (más reciente)" : ""}
                        </option>
                      ))}
                    </select>
                    <button
                      onClick={() => handleRemoveYear(editYear)}
                      disabled={years.length <= 1}
                      title="Elimina este año del histórico para todos los productos"
                      style={{
                        padding: "5px 10px", borderRadius: 6, border: "1px solid #D4CDBB",
                        fontSize: 12, fontWeight: 600,
                        cursor: years.length > 1 ? "pointer" : "not-allowed",
                        background: "white", color: years.length > 1 ? "#A6452E" : "#C9C2B0",
                      }}
                    >
                      Eliminar año
                    </button>
                  </div>
                </div>

                <table style={{ width: "100%", borderCollapse: "collapse", fontSize: 13 }}>
                  <thead>
                    <tr style={{ textAlign: "left", opacity: 0.6, fontSize: 11.5, textTransform: "uppercase" }}>
                      <th style={{ paddingBottom: 6 }}>Tipo</th>
                      <th style={{ paddingBottom: 6 }}>Con IVA</th>
                      <th style={{ paddingBottom: 6 }}>Sin IVA</th>
                      <th style={{ paddingBottom: 6 }}></th>
                    </tr>
                  </thead>
                  <tbody>
                    {CT_ORDER.map((ct) => {
                      const series = selectedRecord.prices[ct] || [];
                      const entry = series.find((p) => p.year === editYear);
                      const prev = prevYearEntry(series, editYear);

                      const applyForecast = () => {
                        if (!prev) return;
                        if (prev.with_vat !== null && prev.with_vat !== undefined) {
                          updatePrice(selected, ct, "with_vat", (Math.round(prev.with_vat * (1 + cpiRate) * 100) / 100).toString(), editYear);
                        }
                        if (prev.no_vat !== null && prev.no_vat !== undefined) {
                          updatePrice(selected, ct, "no_vat", (Math.round(prev.no_vat * (1 + cpiRate) * 100) / 100).toString(), editYear);
                        }
                      };

                      return (
                        <tr key={ct} style={{ borderTop: "1px solid #F0EBDD" }}>
                          <td style={{ padding: "8px 0", fontWeight: 600 }}>
                            <span style={{ display: "inline-block", width: 8, height: 8, borderRadius: "50%", background: CT_COLORS[ct], marginRight: 7 }} />
                            {CT_LABELS[ct]}
                          </td>
                          <td>
                            <input
                              key={`${selected}-${ct}-${editYear}-wv-${entry?.with_vat ?? "empty"}`}
                              type="text" inputMode="decimal"
                              defaultValue={entry?.with_vat ?? ""}
                              placeholder="—"
                              onBlur={(e) => updatePrice(selected, ct, "with_vat", e.target.value, editYear)}
                              style={{ width: 90, padding: "5px 8px", borderRadius: 6, border: "1px solid #D4CDBB",
                                fontSize: 13, background: "#FFFBEA", fontFamily: "inherit", color: "#20242C" }}
                            />
                          </td>
                          <td>
                            <input
                              key={`${selected}-${ct}-${editYear}-nv-${entry?.no_vat ?? "empty"}`}
                              type="text" inputMode="decimal"
                              defaultValue={entry?.no_vat ?? ""}
                              placeholder="—"
                              onBlur={(e) => updatePrice(selected, ct, "no_vat", e.target.value, editYear)}
                              style={{ width: 90, padding: "5px 8px", borderRadius: 6, border: "1px solid #D4CDBB",
                                fontSize: 13, background: "#FFFBEA", fontFamily: "inherit", color: "#20242C" }}
                            />
                          </td>
                          <td style={{ display: "flex", gap: 6 }}>
                            <button
                              onClick={applyForecast}
                              disabled={!prev}
                              title={prev ? `Usar ${fmtEUR(prev.with_vat)} × (1+IPC)` : "Sin año anterior para calcular"}
                              style={{
                                padding: "5px 10px", borderRadius: 6, border: "1px solid #D4CDBB",
                                fontSize: 12, fontWeight: 600, cursor: prev ? "pointer" : "not-allowed",
                                background: prev ? "#EFEAE0" : "#F5F2E9", color: prev ? "#1C2B45" : "#A8A08C",
                              }}
                            >
                              Usar previsión IPC
                            </button>
                            <button
                              onClick={() => {
                                updatePrice(selected, ct, "with_vat", "", editYear);
                                updatePrice(selected, ct, "no_vat", "", editYear);
                              }}
                              disabled={!entry}
                              title="Borra el precio de este tipo para este año (vuelve a quedar sin datos)"
                              style={{
                                padding: "5px 10px", borderRadius: 6, border: "1px solid #D4CDBB",
                                fontSize: 12, fontWeight: 600, cursor: entry ? "pointer" : "not-allowed",
                                background: "white", color: entry ? "#A6452E" : "#C9C2B0",
                              }}
                            >
                              Vaciar
                            </button>
                          </td>
                        </tr>
                      );
                    })}
                  </tbody>
                </table>
              </div>
             

              {/* Cross-type comparison + rosette badge */}
              <div style={{ display: "grid", gridTemplateColumns: "1fr 1fr 1fr auto", gap: 12, marginBottom: 18, alignItems: "stretch" }}>
                <ComparisonCard label="Usuario vs Socio" value={crossTypeVariation.userVsMember} />
                <ComparisonCard label="Colaboradora vs Socio" value={crossTypeVariation.collabVsMember} />
                <ComparisonCard label="Colaboradora vs Usuario" value={crossTypeVariation.collabVsUser} />
                <RosetteBadge value={crossTypeVariation.userVsMember} />
              </div>

              
            </>
          )}
        </div>
      </div>
    </div>
  );
}

function ComparisonCard({ label, value }) {
  return (
    <div style={{
      background: "white", borderRadius: 10, border: "1px solid #E5DFD1",
      padding: "14px 16px", display: "flex", flexDirection: "column", justifyContent: "center",
    }}>
      <div style={{ fontSize: 11.5, opacity: 0.6, marginBottom: 6 }}>{label}</div>
      <div style={{ display: "flex", alignItems: "center", gap: 6, fontSize: 18, fontWeight: 700, fontFamily: "'Georgia', serif" }}>
        <TrendIcon v={value} /> {fmtPct(value)}
      </div>
    </div>
  );
}

function RosetteBadge({ value }) {
  const pct = value !== null && value !== undefined ? Math.abs(value * 100).toFixed(0) : "—";
  return (
    <div style={{
      width: 92, display: "flex", flexDirection: "column", alignItems: "center", justifyContent: "center",
      position: "relative",
    }}>
      <div style={{
        width: 78, height: 78, borderRadius: "50%",
        background: "linear-gradient(135deg, #B98A3F, #8C6B2E)",
        display: "flex", flexDirection: "column", alignItems: "center", justifyContent: "center",
        color: "#FBFAF6", boxShadow: "0 3px 8px rgba(28,43,69,0.25)",
      }}>
        <Award size={16} />
        <div style={{ fontSize: 15, fontWeight: 800, lineHeight: 1 }}>{pct}%</div>
      </div>
      <div style={{ fontSize: 9.5, textAlign: "center", opacity: 0.65, marginTop: 4, lineHeight: 1.2 }}>
        AHORRO
        <br />SOCIO
      </div>
    </div>
  );
}